eBay/evo-web

.changeset/some-games-smile.md, packages/ebayui-core/src/components/components/ebay-notice-base/component.ts, packages/ebayui-core/src/components/components/ebay-notice-base/index.marko, packages/ebayui-core/src/components/ebay-page-notice/component.ts, packages/ebayui-core/src/components/ebay-page-notice/examples/with-custom-cta-dismiss.marko, packages/ebayui-core/src/components/ebay-page-notice/index.marko, packages/ebayui-core/src/components/ebay-page-notice/page-notice.stories.ts, packages/ebayui-core/src/components/ebay-page-notice/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-page-notice/test/test.server.js, packages/ebayui-core/src/components/ebay-section-notice/component.ts, packages/ebayui-core/src/components/ebay-section-notice/examples/with-custom-cta-dismiss.marko, packages/ebayui-core/src/components/ebay-section-notice/index.marko, packages/ebayui-core/src/components/ebay-section-notice/section-notice.stories.ts, packages/ebayui-core/src/components/ebay-section-notice/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-section-notice/test/test.server.js
Fixes #9
* Added support for custom CTA type (using `as`) in notice base
* Added event to emit (`cta-click`)
* Added support/tests/storybook changes in page notice and section notice
=> feat(notice): added support for custom CTA button

.changeset/itchy-kids-visit.md, packages/skin/dist/accordion/accordion.css, packages/skin/src/sass/accordion/accordion.scss
Fixes #5
* Added direct child selector to accordion
=> fix(accordion): added direct child selector to li

.changeset/cold-baths-learn.md, packages/ebayui-core/src/components/ebay-filter-menu-button/component.ts
Fixes #6
* Moved focus to when escape is pressed not when menu is closed
=> fix(filter-menu-button): removed focus from collapse and moved it to escape

.changeset/mean-rabbits-yawn.md, .changeset/public-hands-relate.md, packages/ebayui-core/src/components/ebay-snackbar-dialog/component.ts, packages/ebayui-core/src/components/ebay-snackbar-dialog/examples/action.marko, packages/ebayui-core/src/components/ebay-snackbar-dialog/examples/stacked.marko, packages/ebayui-core/src/components/ebay-snackbar-dialog/index.marko, packages/ebayui-core/src/components/ebay-snackbar-dialog/test/__snapshots__/test.server.js.snap
Fixes #3 #7
* Added a fix to allow open to swap based on input
* Added a fix to pass in actions to fake-button
=> fix(snackbar): open is honored from input and accesskey is spread correctly

.changeset/curvy-peaches-hide.md, packages/skin/dist/ccd/ccd.css, packages/skin/src/routes/_index/component/ccd/+page.marko, packages/skin/src/sass/ccd/ccd.scss
Fixes #47
* Added changes to CCD size and font
* Uploaded new reddit condensed font and use that as the primary font for CCD
=> feat(ccd): updated to latest spec

.changeset/lucky-sheep-hang.md, packages/skin/dist/section-notice/section-notice.css, packages/skin/src/sass/section-notice/section-notice.scss
Fixes https://github.com/eBay/evo-web/issues/82
- Fixed the alignment issue of CTA when the `icon` is set to `none` for small screens.
**Before**
**After**
=> fix(notice): resolve CTA alignment issue for none icon case

.changeset/nine-times-report.md, packages/ebayui-core-react/README.md, packages/ebayui-core-react/src/ebay-ccd/README.md, packages/ebayui-core-react/src/ebay-ccd/__tests__/__snapshots__/render.spec.tsx.snap, packages/ebayui-core-react/src/ebay-ccd/__tests__/index.stories.tsx, packages/ebayui-core-react/src/ebay-ccd/__tests__/render.spec.tsx, packages/ebayui-core-react/src/ebay-ccd/ccd.tsx, packages/ebayui-core-react/src/ebay-ccd/index.ts, packages/ebayui-core/src/components/ebay-ccd/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-ccd/test/test.server.js
Fixes #96 
- Add new EbayCCD react component
- Fix marko `secondaryType` unit test
=> feat(react): add new EbayCCD component

.changeset/wicked-pans-wave.md, packages/ebayui-core-react/README.md, packages/ebayui-core-react/src/ebay-file-input/README.md, packages/ebayui-core-react/src/ebay-file-input/__tests__/__snapshots__/render.spec.tsx.snap, packages/ebayui-core-react/src/ebay-file-input/__tests__/index.stories.tsx, packages/ebayui-core-react/src/ebay-file-input/__tests__/render.spec.tsx, packages/ebayui-core-react/src/ebay-file-input/file-input.tsx, packages/ebayui-core-react/src/ebay-file-input/index.ts, packages/ebayui-core-react/src/ebay-file-input/types.ts
Fixes #98 
- Add new EbayFileInput component
=> feat(react): add new EbayFileInput component

.changeset/purple-colts-thank.md, packages/ebayui-core/README.md, packages/ebayui-core/src/components/ebay-filter-input/README.md, packages/ebayui-core/src/components/ebay-filter-input/browser.json, packages/ebayui-core/src/components/ebay-filter-input/component.ts, packages/ebayui-core/src/components/ebay-filter-input/constants.ts, packages/ebayui-core/src/components/ebay-filter-input/examples/controls.marko, packages/ebayui-core/src/components/ebay-filter-input/examples/default.marko, packages/ebayui-core/src/components/ebay-filter-input/filter-input.stories.ts, packages/ebayui-core/src/components/ebay-filter-input/index.marko, packages/ebayui-core/src/components/ebay-filter-input/style.ts, packages/ebayui-core/src/components/ebay-filter-input/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-filter-input/test/test.browser.js, packages/ebayui-core/src/components/ebay-filter-input/test/test.server.js
Fixes #76
* Coreui version of component
=> feat(filter-input): new component

.changeset/crazy-singers-train.md, packages/ebayui-core-react/smoke-tests/react-16/index.js, packages/ebayui-core-react/src/ebay-dialog-base/__tests__/index.spec.tsx, packages/ebayui-core-react/src/ebay-dialog-base/components/dialogBase.tsx, packages/ebayui-core-react/src/ebay-lightbox-dialog/__tests__/index.spec.tsx
Fixes #144
Change how we handle background click by using the mask as the click handler target. The current approach of adding an event listener in the `document` conflicts on how React handles the states update in the DOM causing issues when apps do state changes that impact in the UI visibility. For example, clicking an `Edit` button, will replace that button with a different `Save` button. This issue has to do how the Event loops works and how the state update is made by React. When clicking a button, each event handler (added with `element.addEventListener`) is going to be considered as a different task in the event loop (unless `element.click()` is being used). React schedules their DOM updates in a micro task, and that micro task will execute before the next task on the event loop, …
=> fix(react:dialog): fix close handler call when the clicked element is removed from the DOM

.changeset/mean-monkeys-pick.md, packages/ebayui-core/src/components/ebay-number-input/component.ts, packages/skin/dist/number-input/number-input.css, packages/skin/src/routes/_index/component/number-input/+page.component-browser.js, packages/skin/src/routes/_index/component/number-input/+page.marko, packages/skin/src/sass/number-input/number-input.scss
- Fixes #130
* Added animations for number input
* The scale ones are set exactly to spec, but are really hard to see IMO. However, thats what the spec says.
* Also updated coreui with changes as well
=> feat(number-input): added animation

src/routes/+layout.style.scss
n/a, I just kept noticing it and it was bothering me 😬 . Can create an issue for tracking purposes if needed.
Just got rid of the `width` CSS property in the evo placeholder page because it was off center and driving me crazy 😆
=> fix(site): removed 90vw width as it was uncentering content in main evo page

.changeset/seven-knives-grow.md, packages/ebayui-core/src/components/components/ebay-dialog-base/index.marko, packages/ebayui-core/src/components/ebay-panel-dialog/examples/with-footer.marko, packages/ebayui-core/src/components/ebay-panel-dialog/examples/with-prev-button.marko, packages/ebayui-core/src/components/ebay-panel-dialog/index.marko, packages/ebayui-core/src/components/ebay-panel-dialog/marko-tag.json, packages/ebayui-core/src/components/ebay-panel-dialog/panel-dialog.stories.ts, packages/ebayui-core/src/components/ebay-panel-dialog/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-panel-dialog/test/test.server.js, packages/skin/dist/panel-dialog/panel-dialog.css, packages/skin/src/routes/_index/component/panel-dialog/+page.marko, packages/skin/src/sass/panel-dialog/panel-dialog.scss, packages/skin/src/sass/panel-dialog/stories/panel-dialog.stories.js
Fixes #165 
- Updated panel dialog styles with prev button styles
- Added a new @prev-button attribute tag to the `ebay-panel-dialog` component, allowing users to include a navigation button for going back to previous screens 
- Updated panel dialog stories, examples and snapshots.
- I had trouble performing percy snapshot test. Ran into few issues.
=> feat(panel-dialog): added prev button

.changeset/fuzzy-colts-share.md, packages/ebayui-core-react/src/ebay-number-input/README.md, packages/ebayui-core-react/src/ebay-number-input/__tests__/index.spec.tsx, packages/ebayui-core-react/src/ebay-number-input/__tests__/index.stories.tsx, packages/ebayui-core-react/src/ebay-number-input/index.ts, packages/ebayui-core-react/src/ebay-number-input/number-input.tsx, packages/ebayui-core-react/src/ebay-number-input/types.ts, packages/ebayui-core-react/src/ebay-textbox/postfix-icon.tsx, packages/ebayui-core-react/src/ebay-textbox/prefix-icon.tsx, packages/ebayui-core-react/src/ebay-textbox/types.ts
Fixes #
- Add `EbayNumberInput` component
- Update definitions of `EbayTextboxPrefixIcon` and `EbayTextboxPostfixIcon` to render child elements
=> feat(react): add new EbayNumberInput component

.github/instructions/skin-css-prompt.instructions.md, .github/instructions/skin-html-prompt.instructions.md, packages/skin/CONTRIBUTING.md, packages/skin/STYLEGUIDE.md
This is for adding a shared set of Copilot instructions for use on local machines.
1. Click on "Add Context"
2. From the selection, select "Instructions..."
3. Load the prompt instruction file(s) from `.github/instructions`
Your Copilot interactions will then take the instructions as context.
Feel free to suggest changes. These were just the initial set of instructions that came to mind for the `scss` and `html`.
=> chore(ai): added the initial shared instructions for copilot

packages/skin/CONTRIBUTING.md, packages/skin/src/components/site-footer.marko, packages/skin/src/components/site-header.marko, packages/skin/src/routes/_index/component/flag/+page.marko, packages/skin/src/routes/_index/component/icon/+page.marko, packages/skin/src/routes/_index/component/svg/+page.marko, packages/skin/src/routes/_index/sitemap+page.marko, packages/skin/src/sass/bundles/skin-default.scss, packages/skin/src/sass/bundles/skin-full.scss
Fixes #197 
- The changes include GitHub repository references throughout the Skin package documentation and source files to reflect the migration from the standalone eBay/skin repository to the monorepo at eBay/evo-web.
-  Updated SVG asset references to point to the new monorepo.
- Also updated the LICENSE text for skin. Not sure if this what I updated is the right way.
=> docs(skin): update github repo links

.changeset/spotty-moles-hunt.md, packages/ebayui-core-react/src/ebay-filter-menu/__tests__/index.stories.tsx, packages/ebayui-core-react/src/ebay-filter-menu/__tests__/render.spec.tsx, packages/ebayui-core-react/src/ebay-filter-menu/filter-menu.tsx
- Make sure to check that the item is not `disabled` before triggering click/keydown events
- Remove "Space" keydown on checkboxes since the onClick is triggered instead
- Correctly check the field when clicking on the label and/or the input field
=> fix(react:filter-menu): avoid checking the item when disabled and fix handlers

.changeset/full-tigers-find.md, packages/skin/dist/svg/icon/icon-ebay-balance-12-colored.svg, packages/skin/dist/svg/icon/icon-ebay-balance-18-colored.svg, packages/skin/dist/svg/icon/icon-ebay-balance-24-colored.svg, packages/skin/dist/svg/icon/icon-ebay-balance-32-colored.svg, packages/skin/dist/svg/icons.svg, packages/skin/src/components/data/icons.json, packages/skin/src/components/master-icons.marko, packages/skin/src/routes/static/icon/icon-ebay-balance-12-colored.svg, packages/skin/src/routes/static/icon/icon-ebay-balance-18-colored.svg, packages/skin/src/routes/static/icon/icon-ebay-balance-24-colored.svg, packages/skin/src/routes/static/icon/icon-ebay-balance-32-colored.svg, packages/skin/src/routes/static/icons.svg, packages/skin/src/svg/icon/icon-ebay-balance-12-colored.svg, packages/skin/src/svg/icon/icon-ebay-balance-18-colored.svg, packages/skin/src/svg/icon/icon-ebay-balance-24-colored.svg, packages/skin/src/svg/icon/icon-ebay-balance-32-colored.svg, packages/skin/src/svg/icons.svg
Fixes #214 
I manually added the missing stroke to the ebay balance icons.
**Before**
<kbd><img width="107" height="104" alt="image" src="https://github.com/user-attachments/assets/251a8d90-d25f-41a5-8e45-43986ee115de" /></kbd>
**After**
<kbd><img width="105" height="105" alt="image" src="https://github.com/user-attachments/assets/8c830561-e351-4819-a1f4-caf2e060aa73" /></kbd>
=> fix(icons): fixed ebay balance icons

.changeset/funny-beans-yell.md, packages/ebayui-core-react/src/common/dropdown.ts, packages/ebayui-core-react/src/ebay-chips-combobox/__tests__/index.spec.tsx, packages/ebayui-core-react/src/ebay-combobox/combobox.tsx
Fixes #
- Initialize makeup-expander only when visibleOptions are available
=> fix(combobox): initialize makeup-expander only when there are visible options

.changeset/tiny-files-kneel.md, packages/ebayui-core-react/src/ebay-tooltip/__tests__/index.spec.tsx, packages/ebayui-core-react/src/ebay-tooltip/ebay-tooltip.tsx
Fixes #235 
- Add `Esc` key press handler on tooltip
=> fix(EbayTooltip): close tooltip on Esc key

.changeset/tidy-sites-poke.md, packages/ebayui-core/src/components/ebay-menu-button/component.ts, packages/ebayui-core/src/components/ebay-menu-button/examples/footer.marko, packages/ebayui-core/src/components/ebay-menu-button/index.marko, packages/ebayui-core/src/components/ebay-menu-button/marko-tag.json, packages/ebayui-core/src/components/ebay-menu-button/menu-button.stories.ts, packages/ebayui-core/src/components/ebay-menu-button/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-menu-button/test/test.server.js, packages/ebayui-core/src/components/ebay-menu/component.ts, packages/ebayui-core/src/components/ebay-menu/examples/footer.marko, packages/ebayui-core/src/components/ebay-menu/index.marko, packages/ebayui-core/src/components/ebay-menu/marko-tag.json, packages/ebayui-core/src/components/ebay-menu/menu.stories.ts, packages/ebayui-core/src/components/ebay-menu/test/__snapshots__/test.server.js.snap, packages/ebayui-core/src/components/ebay-menu/test/test.server.js
Fixes #224
* Added support for footer in menu and menu button. This was in skin already but did not get into coreui.
=> feat(menu): added support for footer element

.changeset/stale-years-walk.md, packages/ebayui-core/src/components/ebay-selection-chip/component.ts
Fixes #270 
* Added state to onCreate and removed mounted changes from onInput
=> fix(selection-chip): moved animated logic to onCreate

.github/ISSUE_TEMPLATE/NEW-FEATURE-REQUEST.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/node.js.yml, .gitignore
Updated the PR template
PLEASE READ before reviewing for explanations. 
* Added a blurb that issue is required. 
* Removed mind patterns checkboxes, those are now part of the create issue template checklist
* I removed the has CSS changes or not. That can be seen in the PR. Also we should be using labels to determine if this is a skin/ebayui/react PR
* I removed the is build in a broken state. This should be determined by the PR CI which should pass before merging a PR
* I moved `I added/updated/removed testing (Storybook in Skin) coverage as appropriate` into all PR types (should have tests updated for ebayui and react too)
* I removed the `I regenerated all CSS files under dist folder`. What I did is update the CI job to fail if there are any uncommited files after running the build. …
=> chore: updated pr and issue templates

.changeset/short-frogs-post.md, packages/ebayui-core/src/components/ebay-filter-chip/component.ts, packages/ebayui-core/src/components/ebay-selection-chip/component.ts
- Fixes #269
Added types for filter chip and selection chip
=> fix(chip): added type for event

.changeset/clear-news-search.md, .changeset/thin-snakes-talk.md, packages/ebayui-core/src/components/ebay-tourtip/component.ts, packages/ebayui-core/src/components/ebay-tourtip/index.marko, packages/ebayui-core/src/components/ebay-tourtip/marko-tag.json, packages/ebayui-core/src/components/ebay-tourtip/tourtip.stories.ts, packages/ebayui-core/src/components/ebay-video/component.ts, packages/ebayui-core/src/components/ebay-video/index.marko
* Video: fixed an issue where the video was being loaded but not shown. This was causing some issues with showing an error in the console because some dom elements werent instantiated by shaka yet
* Video: fixed an issue with the big play button which was bugged and showing weird symbols. I basically just inject a play button container now.
* Video: Fixed an issue where styles were coming in the page as `width: undefinedpx, height: undefinedpx`
* Tourtip: added an override to allow custom containers so that span wasn't the only option. This helps to position of the element correctly if the container needs to be a div
=> fix(video,tourtip): bugs on components

.changeset/petite-swans-drum.md, packages/ebayui-core-react/src/ebay-avatar/__tests__/__snapshots__/render.spec.tsx.snap, packages/ebayui-core-react/src/ebay-avatar/avatar-image.tsx, packages/ebayui-core-react/src/ebay-avatar/avatar.tsx, packages/ebayui-core-react/src/ebay-avatar/context.ts, packages/ebayui-core-react/src/ebay-avatar/utils.ts, packages/ebayui-core-react/src/utils/invariant.ts
Part of #112 
- Remove `findComponents` usage from `EbayAvatar`
- Introduce a context so state update function can be used on the `EbayAvatarImage`
- Move onLoad logic to `EbayAvatarImage` component
This doesn't change any behavior nor API of the component.
=> chore(EbayAvatar): remove usage of React.Children and cloneElement

.changeset/common-pears-move.md, packages/ebayui-core-react/src/ebay-icon-button/README.md, packages/ebayui-core-react/src/ebay-icon-button/__tests__/index.stories.tsx, packages/ebayui-core-react/src/ebay-icon-button/__tests__/render.spec.tsx, packages/ebayui-core-react/src/ebay-icon-button/icon-button.tsx
- Fixes #309 
- Add support for `priority` on `EbayIconButton`
=> feat(EbayIconButton): add support for 'priority' property
